version: '3.8' # Версия синтаксиса docker-compose

services: # Здесь описываются сервисы (контейнеры), которые нужно запустить
  bot: # Название нашего сервиса (может быть любым)
    build: . # Говорим docker-compose, что образ нужно собрать из Dockerfile в текущей директории (.)
    restart: unless-stopped # Перезапускать контейнер, если он упал, но не перезапускать, если был остановлен вручную
    volumes: # Монтируем тома
#      - ./logs:/app/logs # (Опционально) Пример: монтируем папку logs с хоста в контейнер, если будешь писать логи в файл
      - ./voices:/app/voices:rw # Монтируем папку voices, чтобы файлы не терялись между перезапусками контейнера
    env_file: # Загружаем переменные окружения из файла
      - .env # Укажи путь к твоему .env файлу
    environment: # Также можно задавать переменные окружения напрямую здесь
      - PYTHONUNBUFFERED=1 # Полезно для корректного вывода логов из Python в консоль Docker