services: 
  bot: # Название нашего сервиса (может быть любым)
    image: slayem/tg-bot:latest
    pull_policy: always
    restart: unless-stopped 
    volumes: 
      - ./voices:/app/voices:rwx 
      - ./whisper_models:/app/whisper_models:rwx
    env_file: # Загружаем переменные окружения из файла
      - ../.env 
    environment: # Также можно задавать переменные окружения напрямую здесь
      - PYTHONUNBUFFERED=1 