name: home-server-cicd

# trigger - when it runs
on:
  push:
    branches: [ "test-docker-opti" ]

jobs:
  build-n-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo code
        uses: actions/checkout@v4

      - name: setup-docker-buildx
        uses: docker/setup-buildx-action@v3

      - name: login-to-dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build n push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: True
          tags: ${{ secrets.DOCKER_USERNAME }}/tg-bot:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: self-hosted
    needs: build-n-push

    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: create-env-file
        run: |
          echo "${{ secrets.TOKEN }}" > .env

      - name: deploy-with-compose
        run: |
          docker-compose pull
          docker-compose up -d --remove-orphans --force-recreate
          docker image prune -f








